-- Colorscheme WezTerm para Neovim
-- Paleta adaptada del tema personalizado de WezTerm

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "wezterm"
vim.o.termguicolors = true

local p = {
  bg = "#03070d",
  fg = "#d7e9ff",
  cursor = "#00a8ff",
  selection_bg = "#073b63",
  selection_fg = "#ffffff",
  black = "#050b12",
  red = "#ff5577",
  green = "#36d98a",
  yellow = "#ffd166",
  blue = "#249cff",
  magenta = "#a78bfa",
  cyan = "#22d3ee",
  white = "#d7e9ff",
  gray = "#52677d",
  red_b = "#ff6b88",
  green_b = "#5ee7a5",
  yellow_b = "#ffe08a",
  blue_b = "#55b7ff",
  magenta_b = "#c4b5fd",
  cyan_b = "#67e8f9",
  white_b = "#ffffff",
  float_bg = "#071a2b",
  float_border = "#08243a",
  bar_bg = "#02060b",
  line_highlight = "#051321",
}

local hl_groups = {
  -- Interfaz general del editor
  Normal = { fg = p.fg, bg = p.bg },
  NormalNC = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.float_bg },
  FloatBorder = { fg = p.float_border, bg = p.float_bg },
  FloatTitle = { fg = p.cyan, bg = p.float_bg, bold = true },
  FloatFooter = { fg = p.gray, bg = p.float_bg },
  Cursor = { fg = p.bg, bg = p.cursor },
  CursorLine = { bg = p.line_highlight },
  CursorColumn = { bg = p.line_highlight },
  ColorColumn = { bg = p.line_highlight },
  LineNr = { fg = p.gray },
  CursorLineNr = { fg = p.cursor, bold = true },
  SignColumn = { fg = p.gray, bg = p.bg },
  VertSplit = { fg = p.float_border, bg = p.bg },
  WinSeparator = { fg = p.float_border, bg = p.bg },
  StatusLine = { fg = p.fg, bg = p.bar_bg },
  StatusLineNC = { fg = p.gray, bg = p.bar_bg },
  TabLine = { fg = p.gray, bg = p.bar_bg },
  TabLineFill = { bg = p.bar_bg },
  TabLineSel = { fg = p.fg, bg = p.line_highlight, bold = true },

  -- Búsqueda y selección
  Visual = { bg = p.selection_bg },
  VisualNOS = { bg = p.selection_bg },
  Search = { fg = p.selection_fg, bg = p.selection_bg },
  IncSearch = { fg = p.black, bg = p.yellow, bold = true },
  CurSearch = { fg = p.black, bg = p.yellow, bold = true },
  MatchParen = { fg = p.yellow, bg = p.line_highlight, bold = true },

  -- Menús desplegables flotantes (Pmenu)
  Pmenu = { fg = p.fg, bg = p.float_bg },
  PmenuSel = { fg = p.selection_fg, bg = p.selection_bg, bold = true },
  PmenuSbar = { bg = p.float_bg },
  PmenuThumb = { bg = p.gray },
  WildMenu = { fg = p.black, bg = p.cyan },

  -- Mensajes y avisos
  Question = { fg = p.green },
  MoreMsg = { fg = p.green },
  ModeMsg = { fg = p.cyan, bold = true },
  WarningMsg = { fg = p.yellow },
  ErrorMsg = { fg = p.red, bold = true },
  Directory = { fg = p.blue },
  Title = { fg = p.cyan, bold = true },
  Folded = { fg = p.gray, bg = p.line_highlight },
  FoldColumn = { fg = p.gray, bg = p.bg },
  NonText = { fg = p.gray },
  SpecialKey = { fg = p.gray },
  Conceal = { fg = p.gray },

  -- Grupos de sintaxis estándar
  Comment = { fg = p.gray, italic = true },
  Constant = { fg = p.magenta },
  String = { fg = p.green },
  Character = { fg = p.green_b },
  Number = { fg = p.yellow },
  Boolean = { fg = p.yellow_b, bold = true },
  Float = { fg = p.yellow },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.magenta },
  Conditional = { fg = p.magenta },
  Repeat = { fg = p.magenta },
  Label = { fg = p.cyan },
  Operator = { fg = p.cyan },
  Keyword = { fg = p.magenta },
  Exception = { fg = p.red },
  PreProc = { fg = p.cyan },
  Include = { fg = p.cyan },
  Define = { fg = p.magenta },
  Macro = { fg = p.magenta_b },
  PreCondit = { fg = p.cyan },
  Type = { fg = p.yellow },
  StorageClass = { fg = p.yellow },
  Structure = { fg = p.yellow },
  Typedef = { fg = p.yellow },
  Special = { fg = p.cyan },
  SpecialChar = { fg = p.cyan_b },
  Tag = { fg = p.blue },
  Delimiter = { fg = p.fg },
  SpecialComment = { fg = p.gray, italic = true },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = p.red, bold = true },
  Todo = { fg = p.black, bg = p.yellow, bold = true },

  -- Treesitter
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.red },
  ["@variable.parameter"] = { fg = p.cyan },
  ["@variable.member"] = { fg = p.blue_b },
  ["@constant"] = { fg = p.magenta },
  ["@constant.builtin"] = { fg = p.magenta_b, bold = true },
  ["@constant.macro"] = { fg = p.magenta_b },
  ["@keyword"] = { fg = p.magenta },
  ["@keyword.function"] = { fg = p.magenta },
  ["@keyword.return"] = { fg = p.magenta, bold = true },
  ["@keyword.operator"] = { fg = p.cyan },
  ["@keyword.import"] = { fg = p.cyan },
  ["@function"] = { fg = p.blue },
  ["@function.builtin"] = { fg = p.blue_b },
  ["@function.method"] = { fg = p.blue },
  ["@function.call"] = { fg = p.blue },
  ["@function.method.call"] = { fg = p.blue },
  ["@function.macro"] = { fg = p.cyan },
  ["@string"] = { fg = p.green },
  ["@string.escape"] = { fg = p.cyan_b },
  ["@string.regex"] = { fg = p.yellow },
  ["@string.special"] = { fg = p.cyan },
  ["@character"] = { fg = p.green_b },
  ["@number"] = { fg = p.yellow },
  ["@boolean"] = { fg = p.yellow_b, bold = true },
  ["@type"] = { fg = p.yellow },
  ["@type.builtin"] = { fg = p.yellow_b },
  ["@property"] = { fg = p.blue_b },
  ["@operator"] = { fg = p.cyan },
  ["@punctuation.delimiter"] = { fg = p.gray },
  ["@punctuation.bracket"] = { fg = p.fg },
  ["@punctuation.special"] = { fg = p.cyan },
  ["@comment"] = { fg = p.gray, italic = true },
  ["@tag"] = { fg = p.blue },
  ["@tag.attribute"] = { fg = p.cyan },
  ["@tag.delimiter"] = { fg = p.gray },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = p.cyan, bold = true },
  ["@markup.raw"] = { fg = p.green },
  ["@markup.link"] = { fg = p.blue, underline = true },
  ["@markup.list"] = { fg = p.cyan },

  -- Diagnósticos LSP
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { undercurl = true, sp = p.red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.green },
  DiagnosticVirtualTextError = { fg = p.red, bg = "#18070d" },
  DiagnosticVirtualTextWarn = { fg = p.yellow, bg = "#181405" },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = "#051321" },
  DiagnosticVirtualTextHint = { fg = p.cyan, bg = "#04181f" },
  DiagnosticSignError = { fg = p.red },
  DiagnosticSignWarn = { fg = p.yellow },
  DiagnosticSignInfo = { fg = p.blue },
  DiagnosticSignHint = { fg = p.cyan },

  -- GitSigns y Diff
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.yellow },
  GitSignsDelete = { fg = p.red },
  DiffAdd = { fg = p.green, bg = "#041f12" },
  DiffChange = { fg = p.yellow, bg = "#181405" },
  DiffDelete = { fg = p.red, bg = "#18070d" },
  DiffText = { fg = p.white_b, bg = "#073b63" },

  -- Snacks.nvim
  SnacksDashboardHeader = { fg = p.cyan, bold = true },
  SnacksDashboardIcon = { fg = p.blue },
  SnacksDashboardKey = { fg = p.yellow, bold = true },
  SnacksDashboardDesc = { fg = p.fg },
  SnacksDashboardFooter = { fg = p.gray, italic = true },
  SnacksPicker = { fg = p.fg, bg = p.float_bg },
  SnacksPickerBorder = { fg = p.float_border, bg = p.float_bg },
  SnacksPickerTitle = { fg = p.cyan, bg = p.float_bg, bold = true },
  SnacksPickerPrompt = { fg = p.yellow, bg = p.float_bg },
  SnacksPickerMatch = { fg = p.yellow_b, bold = true },
  SnacksIndent = { fg = "#102334" },
  SnacksIndentScope = { fg = p.cursor },

  -- Bufferline
  BufferLineFill = { bg = p.bar_bg },
  BufferLineBackground = { fg = p.gray, bg = p.bar_bg },
  BufferLineBufferVisible = { fg = p.gray, bg = p.bg },
  BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true },
  BufferLineSeparator = { fg = p.bar_bg, bg = p.bar_bg },
  BufferLineSeparatorVisible = { fg = p.bar_bg, bg = p.bg },
  BufferLineSeparatorSelected = { fg = p.bar_bg, bg = p.bg },
  BufferLineIndicatorSelected = { fg = p.cursor, bg = p.bg },
  BufferLineModified = { fg = p.yellow, bg = p.bar_bg },
  BufferLineModifiedVisible = { fg = p.yellow, bg = p.bg },
  BufferLineModifiedSelected = { fg = p.yellow, bg = p.bg },
  BufferLineTab = { fg = p.gray, bg = p.bar_bg },
  BufferLineTabSelected = { fg = p.fg, bg = p.bg, bold = true },
  BufferLineTabClose = { fg = p.red, bg = p.bar_bg },

  -- WhichKey
  WhichKey = { fg = p.cyan },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.gray },
  WhichKeyBorder = { fg = p.float_border, bg = p.float_bg },
  WhichKeyValue = { fg = p.yellow },

  -- Blink.cmp & nvim-cmp
  BlinkCmpMenu = { fg = p.fg, bg = p.float_bg },
  BlinkCmpMenuBorder = { fg = p.float_border, bg = p.float_bg },
  BlinkCmpMenuSelection = { fg = p.selection_fg, bg = p.selection_bg, bold = true },
  BlinkCmpScrollBarThumb = { bg = p.gray },
  BlinkCmpScrollBarGutter = { bg = p.float_bg },
  BlinkCmpLabel = { fg = p.fg },
  BlinkCmpLabelMatch = { fg = p.yellow_b, bold = true },
  BlinkCmpLabelDeprecated = { fg = p.gray, strikethrough = true },
  BlinkCmpDoc = { fg = p.fg, bg = p.float_bg },
  BlinkCmpDocBorder = { fg = p.float_border, bg = p.float_bg },
  BlinkCmpDocCursorLine = { bg = p.line_highlight },
  BlinkCmpSignatureHelp = { fg = p.fg, bg = p.float_bg },
  BlinkCmpSignatureHelpBorder = { fg = p.float_border, bg = p.float_bg },
  BlinkCmpKind = { fg = p.cyan },
  BlinkCmpKindText = { fg = p.fg },
  BlinkCmpKindMethod = { fg = p.blue },
  BlinkCmpKindFunction = { fg = p.blue },
  BlinkCmpKindConstructor = { fg = p.blue_b },
  BlinkCmpKindField = { fg = p.blue_b },
  BlinkCmpKindVariable = { fg = p.fg },
  BlinkCmpKindClass = { fg = p.yellow },
  BlinkCmpKindInterface = { fg = p.yellow },
  BlinkCmpKindModule = { fg = p.cyan },
  BlinkCmpKindProperty = { fg = p.blue_b },
  BlinkCmpKindUnit = { fg = p.magenta },
  BlinkCmpKindValue = { fg = p.yellow },
  BlinkCmpKindEnum = { fg = p.yellow },
  BlinkCmpKindKeyword = { fg = p.magenta },
  BlinkCmpKindSnippet = { fg = p.green },
  BlinkCmpKindColor = { fg = p.cyan_b },
  BlinkCmpKindFile = { fg = p.fg },
  BlinkCmpKindReference = { fg = p.cyan },
  BlinkCmpKindFolder = { fg = p.blue },
  BlinkCmpKindEnumMember = { fg = p.yellow_b },
  BlinkCmpKindConstant = { fg = p.magenta },
  BlinkCmpKindStruct = { fg = p.yellow },
  BlinkCmpKindEvent = { fg = p.cyan },
  BlinkCmpKindOperator = { fg = p.cyan },
  BlinkCmpKindTypeParameter = { fg = p.yellow },
  CmpItemAbbr = { fg = p.fg },
  CmpItemAbbrDeprecated = { fg = p.gray, strikethrough = true },
  CmpItemAbbrMatch = { fg = p.yellow_b, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.yellow_b, bold = true },
  CmpItemMenu = { fg = p.gray },
  CmpItemKind = { fg = p.cyan },

  -- RenderMarkdown
  RenderMarkdownH1 = { fg = p.cyan, bold = true },
  RenderMarkdownH2 = { fg = p.blue, bold = true },
  RenderMarkdownH3 = { fg = p.magenta, bold = true },
  RenderMarkdownH4 = { fg = p.yellow, bold = true },
  RenderMarkdownH5 = { fg = p.green, bold = true },
  RenderMarkdownH6 = { fg = p.gray, bold = true },
  RenderMarkdownCode = { bg = p.line_highlight },
  RenderMarkdownBullet = { fg = p.cyan },
  RenderMarkdownTableHead = { fg = p.blue, bold = true },
  RenderMarkdownTableRow = { fg = p.fg },
}

for group, opts in pairs(hl_groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
